//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AircraftManagement
{
    public partial class Profile
    {
        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// imgProfile control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgProfile;

        /// <summary>
        /// lblUsername control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblUsername;

        /// <summary>
        /// lblRole control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblRole;

        /// <summary>
        /// lblCreatedAt control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCreatedAt;

        /// <summary>
        /// btnEditProfile control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnEditProfile;

        /// <summary>
        /// lblProfileCompletion control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblProfileCompletion;

        /// <summary>
        /// lblUsernameDetail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblUsernameDetail;

        /// <summary>
        /// lblEmailDetail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblEmailDetail;

        /// <summary>
        /// lblPhone control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPhone;

        /// <summary>
        /// lblDateOfBirth control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblDateOfBirth;

        /// <summary>
        /// lblGender control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblGender;

        /// <summary>
        /// lblCountry control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCountry;

        /// <summary>
        /// lblBio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblBio;

        /// <summary>
        /// rptBookings control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptBookings;

        /// <summary>
        /// rptActivityLog control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptActivityLog;

        /// <summary>
        /// rptViewedAircraft control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptViewedAircraft;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}
